runtime: node010

run: node example.js

test: |
  if [[ -n "$ROCK_ARGV" ]]; then
    exec mocha --recursive --reporter spec "${ARGV[@]}"
  else
    {{ parent }}
  fi

coverage: |
  istanbul cover _mocha -- --recursive
  if type -f open &>/dev/null; then
    open coverage/lcov-report/index.html
  fi
